// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiCOybJTIX6FEh-VDxzO-MAcmuzg6WPps',
    appId: '1:809830295204:web:5cf586a597abbc4f40e831',
    messagingSenderId: '809830295204',
    projectId: 'studywithme-3da3e',
    authDomain: 'studywithme-3da3e.firebaseapp.com',
    storageBucket: 'studywithme-3da3e.firebasestorage.app',
    measurementId: 'G-L8CS5K9NZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmS-7g4QnG15niJSfao7lbgANnu0I1cw0',
    appId: '1:809830295204:android:4b77c0fd4507eb3140e831',
    messagingSenderId: '809830295204',
    projectId: 'studywithme-3da3e',
    storageBucket: 'studywithme-3da3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKQn6T_YaY4ft0GhuBU-TT7ckWOWKskBU',
    appId: '1:809830295204:ios:c299fb51e9056a3040e831',
    messagingSenderId: '809830295204',
    projectId: 'studywithme-3da3e',
    storageBucket: 'studywithme-3da3e.firebasestorage.app',
    iosBundleId: 'com.example.studyWithMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKQn6T_YaY4ft0GhuBU-TT7ckWOWKskBU',
    appId: '1:809830295204:ios:c299fb51e9056a3040e831',
    messagingSenderId: '809830295204',
    projectId: 'studywithme-3da3e',
    storageBucket: 'studywithme-3da3e.firebasestorage.app',
    iosBundleId: 'com.example.studyWithMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiCOybJTIX6FEh-VDxzO-MAcmuzg6WPps',
    appId: '1:809830295204:web:5242ebd9560c52bb40e831',
    messagingSenderId: '809830295204',
    projectId: 'studywithme-3da3e',
    authDomain: 'studywithme-3da3e.firebaseapp.com',
    storageBucket: 'studywithme-3da3e.firebasestorage.app',
    measurementId: 'G-WKM4HS5M9N',
  );
}
